### ISSUE TITLE
魅族note2 Android5.1 Flyme 6.3.5.0A异常报错

### ISSUE THREAD

**Issue by Kotlin2022** [anyRTC-UseCase/ScreenShare#1]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtf_lite.so"...

**Comment by Kotlin2022** [comment]
09-01 11:38:02.188 7288-7288/org.ar.screenshare E/art: dlopen("/data/app/org.ar.screenshare-2/lib/arm64/libarrtc.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtf_lite.so"...
09-01 11:38:02.189 7288-7288/org.ar.screenshare E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ar.screenshare, PID: 7288
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtf_lite.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:988)
        at org.ar.rtc.RtcEngineImpl.loadNativeLibrary(RtcEngineImpl.java:153)
        at org.ar.rtc.RtcEngineImpl.initializeNativeLibs(RtcEngineImpl.java:172)
        at org.ar.rtc.RtcEngine.create(RtcEngine.java:36)
        at org.ar.screenshare.App.onCreate(App.kt:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5106)
        at android.app.ActivityThread.access$1600(ActivityThread.java:187)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1645)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5898)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by LxzBUG** [comment]
@Android-KJY 更新下demo 升级了sdk

**Comment by Android-KJY** [comment]
ok

**Comment by Kotlin2022** [comment]
> @Android-KJY 更新下demo 升级了sdk

ok
